"""Initial migration

Revision ID: 335f15b7656f
Revises: 
Create Date: 2024-08-08 13:39:59.144630

"""
from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision = '335f15b7656f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),  # Use sa.String
        sa.Column('password', sa.String(length=255), nullable=False),  # Use sa.String
        sa.Column('user_token', sa.String(length=255), nullable=False),  # Use sa.String
        sa.Column('name', sa.String(length=255), nullable=True),  # Use sa.String
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('user_token')
    )
   op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.String(length=255), nullable=False),  # Use sa.String
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('chat_id', sa.String(length=255), nullable=False),  # Use sa.String
        sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('user')
    # ### end Alembic commands ###
